[package]
name = "ethir-gas-report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.1"
eyre = "0.6.8"
tokio = "1.26.0"
